---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ice-driver-containerfile-cm-1.12.18
  namespace: openshift-kmm
data:
  dockerfile: |
    ARG DTK_AUTO
    FROM ${DTK_AUTO} as builder
    ARG KERNEL_VERSION
    WORKDIR /usr/src
    RUN curl -X GET http://192.168.58.15/iso/ice-1.12.18.tar.gz --output ice-1.12.18.tar.gz
    RUN tar -xvf ice-1.12.18.tar.gz
    WORKDIR /usr/src/ice-1.12.18/src
    RUN make install KSRC=/usr/src/kernels/\${KERNEL_VERSION}

    FROM registry.redhat.io/ubi9/ubi-minimal
    ARG KERNEL_VERSION
    RUN microdnf install kmod -y
    RUN mkdir -p /opt/lib/modules/${KERNEL_VERSION}
    COPY --from=builder /usr/lib/modules/${KERNEL_VERSION}/updates/drivers/net/ethernet/intel/ice/ice.ko /opt/lib/modules/${KERNEL_VERSION}/
    RUN ls /opt/lib/modules/${KERNEL_VERSION}
    RUN depmod -b /opt ${KERNEL_VERSION}