---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ice-driver-1.14.13-build
  namespace: openshift-kmm
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: ice
      kernelMappings:
        - regexp: '^.*\.x86_64$'
          containerImage: "quay.io/bzhai/kmm-ice-driver:${KERNEL_FULL_VERSION}-1.14.13"
          build:
            dockerfileConfigMap:
              name: ice-driver-containerfile-cm-1.14.13
  imageRepoSecret:
    name: pull-secret
  selector:
    node-role.kubernetes.io/master: ""