---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ice-driver-1.12.18-build
  namespace: openshift-kmm
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: ice
      kernelMappings:
        - regexp: '^.*\.x86_64$'
          containerImage: "quay.io/bzhai/kmm-ice-driver-1.12.18:${KERNEL_FULL_VERSION}"
          build:
            dockerfileConfigMap:
              name: ice-driver-containerfile-cm-1.12.18
  imageRepoSecret:
    name: pull-secret
  selector:
    node-role.kubernetes.io/master: ""