apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 10-install-oot-MODULE_NAME-mc
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Replace in-tree kernel module with oot kernel module
            Before=network-pre.target
            Wants=network-pre.target
            DefaultDependencies=no
            [Service]
            User=root
            Type=oneshot
            TimeoutSec=10
            EnvironmentFile=/etc/mco/proxy.env
            Environment="IN_TREE_MODULE_TO_REMOVE=MODULE_NAME"
            Environment="KERNEL_MODULE=MODULE_NAME"
            Environment="KERNEL_MODULE_IMAGE_FILEPATH=/var/lib/image_file_day1.tar"
            Environment="WORKER_CONFIG_FILEPATH=/var/lib/kmm_day1_config.yaml"
            Environment="WORKER_IMAGE=quay.io/edge-infrastructure/kernel-module-management-worker:latest"
            ExecStartPre=ls /usr/local/bin
            ExecStart=/usr/local/bin/replace-kernel-module.sh
            PrivateTmp=yes
            RemainAfterExit=no
            TimeoutSec=60
            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: "replace-kernel-module.service"
        - contents: |
            [Unit]
            Description=Pull oot kernel module image
            After=network-online.target
            After=NetworkManager-dispatcher.service
            DefaultDependencies=no
            [Service]
            User=root
            Type=oneshot
            EnvironmentFile=/etc/mco/proxy.env
            Environment="KERNEL_MODULE_IMAGE=MODULE_IMAGE_REPO"
            Environment="KERNEL_MODULE_IMAGE_FILEPATH=/var/lib/image_file_day1.tar"
            Environment="WORKER_IMAGE=quay.io/edge-infrastructure/kernel-module-management-worker:latest"
            ExecStartPre=/usr/local/bin/wait-for-dispatcher.sh
            ExecStart=/usr/local/bin/pull-kernel-module-image.sh
            PrivateTmp=yes
            RemainAfterExit=no
            TimeoutSec=900
            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: "pull-kernel-module-image.service"
        - enabled: false
          mask: true
          name: crio-wipe.service
    storage:
      files:
        - path: "/usr/local/bin/replace-kernel-module.sh"
          mode: 511
          overwrite: true
          user:
            name: "root"
          contents:
            source: "data:text/plain;base64,SCRIPT_REPLACE_KERNEL_MODULE"
        - path: "/usr/local/bin/pull-kernel-module-image.sh"
          mode: 493
          overwrite: true
          user:
            name: "root"
          contents:
            source: "data:text/plain;base64,SCRIPT_PULL_OOT_IMAGE"
        - path: "/usr/local/bin/wait-for-dispatcher.sh"
          mode: 493
          overwrite: true
          user:
            name: "root"
          contents:
            source: "data:text/plain;base64,SCRIPT_WAIT_FOR_DISPATCHER"
